"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Copy, Download, ExternalLink, FolderOpen, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { filesApi, getApiToken, type LocalSyncManifest } from "@/lib/api";
import { toast } from "@/hooks/useToast";
import { cn } from "@/lib/utils";

function defaultLocalDir(serviceId: string) {
  return `./vivox-server-files-${serviceId.slice(0, 8)}`;
}

function buildNodeCommand(manifest: LocalSyncManifest, token: string, localDir: string) {
  const origin =
    typeof window !== "undefined" ? window.location.origin : "http://localhost:3000";
  const scriptUrl = `${origin}${manifest.sync_script_url}`;
  return `node "${scriptUrl}" --service-id ${manifest.service_id} --token "${token}" --api-base "${manifest.api_base}" --local-dir "${localDir}" --pull`;
}

function buildPs1(manifest: LocalSyncManifest, token: string, localDir: string) {
  const origin =
    typeof window !== "undefined" ? window.location.origin : "http://localhost:3000";
  const scriptUrl = `${origin}${manifest.sync_script_url}`;
  return `# Vivox local file sync — generated by Vivox panel
$ErrorActionPreference = "Stop"
$LocalDir = "${localDir.replace(/\\/g, "\\\\")}"
New-Item -ItemType Directory -Force -Path $LocalDir | Out-Null
node "${scriptUrl}" \`
  --service-id "${manifest.service_id}" \`
  --token "${token}" \`
  --api-base "${manifest.api_base}" \`
  --local-dir $LocalDir \`
  --pull
`;
}

function buildSh(manifest: LocalSyncManifest, token: string, localDir: string) {
  const origin =
    typeof window !== "undefined" ? window.location.origin : "http://localhost:3000";
  const scriptUrl = `${origin}${manifest.sync_script_url}`;
  return `#!/usr/bin/env bash
set -euo pipefail
LOCAL_DIR="${localDir}"
mkdir -p "$LOCAL_DIR"
node "${scriptUrl}" \\
  --service-id "${manifest.service_id}" \\
  --token "${token}" \\
  --api-base "${manifest.api_base}" \\
  --local-dir "$LOCAL_DIR" \\
  --pull
`;
}

function downloadText(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function LocalSyncModal({
  serviceId,
  onClose,
}: {
  serviceId: string;
  onClose: () => void;
}) {
  const [manifest, setManifest] = useState<LocalSyncManifest | null>(null);
  const [loading, setLoading] = useState(true);
  const [localDir, setLocalDir] = useState(() => defaultLocalDir(serviceId));
  const token = getApiToken() ?? "";

  useEffect(() => {
    void filesApi
      .localSyncManifest(serviceId)
      .then(setManifest)
      .catch((e) => {
        toast(e instanceof Error ? e.message : "Could not load sync manifest", "error");
      })
      .finally(() => setLoading(false));
  }, [serviceId]);

  const nodeCmd = useMemo(
    () => (manifest && token ? buildNodeCommand(manifest, token, localDir) : ""),
    [manifest, token, localDir],
  );

  const copy = useCallback(async (text: string, label: string) => {
    try {
      await navigator.clipboard.writeText(text);
      toast(`${label} copied`, "success");
    } catch {
      toast(`Could not copy ${label}`, "error");
    }
  }, []);

  const openInVsCode = () => {
    const abs = localDir.startsWith("./")
      ? `${typeof window !== "undefined" ? window.location.pathname : ""}${localDir.slice(1)}`
      : localDir;
    window.location.href = `vscode://file/${encodeURIComponent(abs)}`;
    toast("Opening folder in VS Code (requires local path to exist)", "info");
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm"
      onClick={onClose}
    >
      <div
        className="max-h-[90vh] w-full max-w-xl overflow-auto rounded-xl border border-border bg-surface p-5 shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-start justify-between gap-3">
          <div>
            <h2 className="text-lg font-semibold text-foreground">Local VS Code sync</h2>
            <p className="mt-1 text-sm text-muted">
              Mirror server files to a folder on your machine and edit in VS Code.
            </p>
          </div>
          <button type="button" onClick={onClose} className="rounded-lg p-1 text-muted hover:bg-surface-raised">
            <X className="size-5" />
          </button>
        </div>

        {loading ? (
          <p className="mt-4 text-sm text-muted">Loading sync manifest…</p>
        ) : !manifest ? (
          <p className="mt-4 text-sm text-red-400">Sync manifest unavailable.</p>
        ) : (
          <div className="mt-4 space-y-4 text-sm">
            <ol className="list-decimal space-y-2 pl-4 text-muted">
              <li>
                Download the sync script:{" "}
                <a
                  href={manifest.sync_script_url}
                  download="vivox-file-sync.mjs"
                  className="text-vivox-400 hover:underline"
                >
                  vivox-file-sync.mjs
                </a>
              </li>
              <li>Copy your session JWT and keep it private.</li>
              <li>Choose a local folder and run the generated starter script.</li>
            </ol>

            <label className="flex flex-col gap-1.5">
              <span className="text-xs uppercase tracking-wider text-muted">Local folder</span>
              <input
                value={localDir}
                onChange={(e) => setLocalDir(e.target.value)}
                className="h-9 rounded-lg border border-border bg-background/50 px-3 font-mono text-xs text-foreground outline-none focus:border-border-focus focus:ring-1 focus:ring-border-focus"
              />
            </label>

            <div className="rounded-lg border border-border bg-background/40 p-3">
              <div className="flex items-center justify-between gap-2">
                <p className="text-xs font-medium text-foreground">Session JWT</p>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-7 px-2"
                  disabled={!token}
                  onClick={() => void copy(token, "JWT")}
                >
                  <Copy className="size-3.5" /> Copy JWT
                </Button>
              </div>
              <p className={cn("mt-1 break-all font-mono text-[10px]", token ? "text-muted" : "text-amber-400")}>
                {token ? `${token.slice(0, 24)}…` : "Waiting for session token — refresh if empty"}
              </p>
            </div>

            <div className="rounded-lg border border-border bg-background/40 p-3">
              <div className="flex items-center justify-between gap-2">
                <p className="text-xs font-medium text-foreground">Run command</p>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-7 px-2"
                  disabled={!nodeCmd}
                  onClick={() => void copy(nodeCmd, "command")}
                >
                  <Copy className="size-3.5" /> Copy
                </Button>
              </div>
              <pre className="mt-2 max-h-28 overflow-auto whitespace-pre-wrap break-all font-mono text-[10px] text-muted">
                {nodeCmd || "JWT required to build command"}
              </pre>
            </div>

            <div className="flex flex-wrap gap-2">
              <Button
                variant="outline"
                size="sm"
                disabled={!token}
                onClick={() => {
                  if (!manifest || !token) return;
                  downloadText("start-vivox-sync.ps1", buildPs1(manifest, token, localDir));
                }}
              >
                <Download className="size-3.5" /> start-vivox-sync.ps1
              </Button>
              <Button
                variant="outline"
                size="sm"
                disabled={!token}
                onClick={() => {
                  if (!manifest || !token) return;
                  downloadText("start-vivox-sync.sh", buildSh(manifest, token, localDir));
                }}
              >
                <Download className="size-3.5" /> start-vivox-sync.sh
              </Button>
              <Button variant="secondary" size="sm" onClick={openInVsCode}>
                <FolderOpen className="size-3.5" /> Open in VS Code
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => window.open("https://code.visualstudio.com/", "_blank")}
              >
                <ExternalLink className="size-3.5" /> Get VS Code
              </Button>
            </div>

            <p className="text-xs text-subtle">{manifest.token_hint}</p>
          </div>
        )}
      </div>
    </div>
  );
}
