// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/nexus-control/packages/domain"
)

type DeployStatus string

const (
	DeployStatusQueued   DeployStatus = "queued"
	DeployStatusBuilding DeployStatus = "building"
	DeployStatusSuccess  DeployStatus = "success"
	DeployStatusFailed   DeployStatus = "failed"
)

func (e *DeployStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeployStatus(s)
	case string:
		*e = DeployStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeployStatus: %T", src)
	}
	return nil
}

type NullDeployStatus struct {
	DeployStatus DeployStatus `json:"deploy_status"`
	Valid        bool         `json:"valid"` // Valid is true if DeployStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeployStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeployStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeployStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeployStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeployStatus), nil
}

type ServiceStatus string

const (
	ServiceStatusPROVISIONING ServiceStatus = "PROVISIONING"
	ServiceStatusSTARTING     ServiceStatus = "STARTING"
	ServiceStatusRUNNING      ServiceStatus = "RUNNING"
	ServiceStatusSTOPPING     ServiceStatus = "STOPPING"
	ServiceStatusSTOPPED      ServiceStatus = "STOPPED"
	ServiceStatusCRASHED      ServiceStatus = "CRASHED"
)

func (e *ServiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServiceStatus(s)
	case string:
		*e = ServiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ServiceStatus: %T", src)
	}
	return nil
}

type NullServiceStatus struct {
	ServiceStatus ServiceStatus `json:"service_status"`
	Valid         bool          `json:"valid"` // Valid is true if ServiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ServiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServiceStatus), nil
}

type ServiceType string

const (
	ServiceTypeGame     ServiceType = "game"
	ServiceTypeDocker   ServiceType = "docker"
	ServiceTypeDatabase ServiceType = "database"
	ServiceTypeStatic   ServiceType = "static"
)

func (e *ServiceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServiceType(s)
	case string:
		*e = ServiceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ServiceType: %T", src)
	}
	return nil
}

type NullServiceType struct {
	ServiceType ServiceType `json:"service_type"`
	Valid       bool        `json:"valid"` // Valid is true if ServiceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServiceType) Scan(value interface{}) error {
	if value == nil {
		ns.ServiceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServiceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServiceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServiceType), nil
}

type TaskStatus string

const (
	TaskStatusActive  TaskStatus = "active"
	TaskStatusPaused  TaskStatus = "paused"
	TaskStatusRunning TaskStatus = "running"
	TaskStatusFailed  TaskStatus = "failed"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type AlertMetric string

const (
	AlertMetricCpu    AlertMetric = "cpu"
	AlertMetricMemory AlertMetric = "memory"
)

type AlertOperator string

const (
	AlertOperatorGt AlertOperator = "gt"
	AlertOperatorLt AlertOperator = "lt"
)

type AlertRule struct {
	ID          pgtype.UUID        `json:"id"`
	ServiceID   pgtype.UUID        `json:"service_id"`
	OwnerID     string             `json:"owner_id"`
	Metric      AlertMetric        `json:"metric"`
	Operator    AlertOperator      `json:"operator"`
	Threshold   int32              `json:"threshold"`
	Enabled     bool               `json:"enabled"`
	NotifiedAt  pgtype.Timestamptz `json:"notified_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BackupStatus string

const (
	BackupStatusPending BackupStatus = "pending"
	BackupStatusRunning BackupStatus = "running"
	BackupStatusSuccess BackupStatus = "success"
	BackupStatusFailed  BackupStatus = "failed"
)

type Backup struct {
	ID             pgtype.UUID        `json:"id"`
	ServiceID      pgtype.UUID        `json:"service_id"`
	NodeID         pgtype.UUID        `json:"node_id"`
	Status         BackupStatus       `json:"status"`
	SizeBytes      pgtype.Int8        `json:"size_bytes"`
	Error          pgtype.Text        `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	ConfigSnapshot pgtype.Text        `json:"config_snapshot"` // JSON: {environment, startup_cmd}
}

type DomainStatus string

const (
	DomainStatusPending DomainStatus = "pending"
	DomainStatusActive  DomainStatus = "active"
	DomainStatusError   DomainStatus = "error"
)

type ServiceDomain struct {
	ID        pgtype.UUID        `json:"id"`
	ServiceID pgtype.UUID        `json:"service_id"`
	OwnerID   string             `json:"owner_id"`
	Domain    string             `json:"domain"`
	Status    DomainStatus       `json:"status"`
	Error     pgtype.Text        `json:"error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WebhookConfig struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	URL         string             `json:"url"`
	Secret      pgtype.Text        `json:"secret"`
	Events      []string           `json:"events"`
	Enabled     bool               `json:"enabled"`
	LastFiredAt pgtype.Timestamptz `json:"last_fired_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     string             `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	KeyPrefix  string             `json:"key_prefix"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditEvent struct {
	ID         pgtype.UUID        `json:"id"`
	ActorID    string             `json:"actor_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Deployment struct {
	ID        pgtype.UUID        `json:"id"`
	ServiceID pgtype.UUID        `json:"service_id"`
	CommitSha *string            `json:"commit_sha"`
	Status    DeployStatus       `json:"status"`
	LogsRef   *string            `json:"logs_ref"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Node struct {
	ID             pgtype.UUID         `json:"id"`
	Name           string              `json:"name"`
	Region         string              `json:"region"`
	AgentTokenHash string              `json:"agent_token_hash"`
	Status         string              `json:"status"`
	Capacity       domain.NodeCapacity `json:"capacity"`
	CreatedAt      pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz  `json:"updated_at"`
}

type ScheduledTask struct {
	ID         pgtype.UUID        `json:"id"`
	ServiceID  pgtype.UUID        `json:"service_id"`
	OwnerID    string             `json:"owner_id"`
	Name       string             `json:"name"`
	CronExpr   string             `json:"cron_expr"`
	Action     string             `json:"action"`
	Status     TaskStatus         `json:"status"`
	LastRunAt  pgtype.Timestamptz `json:"last_run_at"`
	NextRunAt  pgtype.Timestamptz `json:"next_run_at"`
	LastResult *string            `json:"last_result"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID             pgtype.UUID           `json:"id"`
	OwnerID        string                `json:"owner_id"`
	TeamID         *string               `json:"team_id"`
	Name           string                `json:"name"`
	Type           ServiceType           `json:"type"`
	Status         ServiceStatus         `json:"status"`
	NodeID         pgtype.UUID           `json:"node_id"`
	ResourceLimits domain.ResourceLimits `json:"resource_limits"`
	Config         domain.ServiceConfig  `json:"config"`
	Tags           []string              `json:"tags"`
	CreatedAt      pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz    `json:"updated_at"`
}
