// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/nexus-control/packages/domain"
)

const createApiKey = `-- name: CreateApiKey :one

INSERT INTO api_keys (user_id, name, key_hash, key_prefix)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, key_hash, key_prefix, last_used_at, created_at
`

type CreateApiKeyParams struct {
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	KeyHash   string `json:"key_hash"`
	KeyPrefix string `json:"key_prefix"`
}

// ============================================================================
// API keys
// ============================================================================
func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one

INSERT INTO deployments (service_id, commit_sha, status, logs_ref)
VALUES ($1, $2, $3, $4)
RETURNING id, service_id, commit_sha, status, logs_ref, created_at
`

type CreateDeploymentParams struct {
	ServiceID pgtype.UUID  `json:"service_id"`
	CommitSha *string      `json:"commit_sha"`
	Status    DeployStatus `json:"status"`
	LogsRef   *string      `json:"logs_ref"`
}

// ============================================================================
// Deployments
// ============================================================================
func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ServiceID,
		arg.CommitSha,
		arg.Status,
		arg.LogsRef,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.CommitSha,
		&i.Status,
		&i.LogsRef,
		&i.CreatedAt,
	)
	return i, err
}

const createNode = `-- name: CreateNode :one

INSERT INTO nodes (name, region, agent_token_hash, status, capacity)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, region, agent_token_hash, status, capacity, created_at, updated_at
`

type CreateNodeParams struct {
	Name           string              `json:"name"`
	Region         string              `json:"region"`
	AgentTokenHash string              `json:"agent_token_hash"`
	Status         string              `json:"status"`
	Capacity       domain.NodeCapacity `json:"capacity"`
}

// ============================================================================
// Nodes
// ============================================================================
func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.Name,
		arg.Region,
		arg.AgentTokenHash,
		arg.Status,
		arg.Capacity,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.AgentTokenHash,
		&i.Status,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScheduledTask = `-- name: CreateScheduledTask :one

INSERT INTO scheduled_tasks (service_id, owner_id, name, cron_expr, action, status, next_run_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, service_id, owner_id, name, cron_expr, action, status, last_run_at, next_run_at, last_result, created_at, updated_at
`

type CreateScheduledTaskParams struct {
	ServiceID pgtype.UUID        `json:"service_id"`
	OwnerID   string             `json:"owner_id"`
	Name      string             `json:"name"`
	CronExpr  string             `json:"cron_expr"`
	Action    string             `json:"action"`
	Status    TaskStatus         `json:"status"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

// ============================================================================
// Scheduled tasks
// ============================================================================
func (q *Queries) CreateScheduledTask(ctx context.Context, arg CreateScheduledTaskParams) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, createScheduledTask,
		arg.ServiceID,
		arg.OwnerID,
		arg.Name,
		arg.CronExpr,
		arg.Action,
		arg.Status,
		arg.NextRunAt,
	)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.OwnerID,
		&i.Name,
		&i.CronExpr,
		&i.Action,
		&i.Status,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.LastResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one

INSERT INTO services (owner_id, team_id, name, type, status, node_id, resource_limits, config)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_id, team_id, name, type, status, node_id, resource_limits, config, tags, created_at, updated_at
`

type CreateServiceParams struct {
	OwnerID        string                `json:"owner_id"`
	TeamID         *string               `json:"team_id"`
	Name           string                `json:"name"`
	Type           ServiceType           `json:"type"`
	Status         ServiceStatus         `json:"status"`
	NodeID         pgtype.UUID           `json:"node_id"`
	ResourceLimits domain.ResourceLimits `json:"resource_limits"`
	Config         domain.ServiceConfig  `json:"config"`
}

// ============================================================================
// Services
// ============================================================================
func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.OwnerID,
		arg.TeamID,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.NodeID,
		arg.ResourceLimits,
		arg.Config,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TeamID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.NodeID,
		&i.ResourceLimits,
		&i.Config,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApiKey = `-- name: DeleteApiKey :exec
DELETE FROM api_keys
WHERE id = $1 AND user_id = $2
`

type DeleteApiKeyParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteApiKey(ctx context.Context, arg DeleteApiKeyParams) error {
	_, err := q.db.Exec(ctx, deleteApiKey, arg.ID, arg.UserID)
	return err
}

const deleteScheduledTask = `-- name: DeleteScheduledTask :exec
DELETE FROM scheduled_tasks
WHERE id = $1 AND service_id = $2
`

type DeleteScheduledTaskParams struct {
	ID        pgtype.UUID `json:"id"`
	ServiceID pgtype.UUID `json:"service_id"`
}

func (q *Queries) DeleteScheduledTask(ctx context.Context, arg DeleteScheduledTaskParams) error {
	_, err := q.db.Exec(ctx, deleteScheduledTask, arg.ID, arg.ServiceID)
	return err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services
WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, user_id, name, key_hash, key_prefix, last_used_at, created_at FROM api_keys
WHERE key_hash = $1
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, name, region, agent_token_hash, status, capacity, created_at, updated_at FROM nodes
WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id pgtype.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.AgentTokenHash,
		&i.Status,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeByTokenHash = `-- name: GetNodeByTokenHash :one
SELECT id, name, region, agent_token_hash, status, capacity, created_at, updated_at FROM nodes
WHERE agent_token_hash = $1
`

func (q *Queries) GetNodeByTokenHash(ctx context.Context, agentTokenHash string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByTokenHash, agentTokenHash)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.AgentTokenHash,
		&i.Status,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getService = `-- name: GetService :one
SELECT id, owner_id, team_id, name, type, status, node_id, resource_limits, config, tags, created_at, updated_at FROM services
WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TeamID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.NodeID,
		&i.ResourceLimits,
		&i.Config,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec

INSERT INTO audit_events (actor_id, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditEventParams struct {
	ActorID    string `json:"actor_id"`
	Action     string `json:"action"`
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
	Metadata   []byte `json:"metadata"`
}

// ============================================================================
// Audit events
// ============================================================================
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	return err
}

const listAllServices = `-- name: ListAllServices :many
SELECT id, owner_id, team_id, name, type, status, node_id, resource_limits, config, tags, created_at, updated_at FROM services
ORDER BY created_at DESC
`

func (q *Queries) ListAllServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.TeamID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.NodeID,
			&i.ResourceLimits,
			&i.Config,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiKeysByUser = `-- name: ListApiKeysByUser :many
SELECT id, user_id, name, key_hash, key_prefix, last_used_at, created_at FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListApiKeysByUser(ctx context.Context, userID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_id, action, target_type, target_id, metadata, created_at FROM audit_events
WHERE ($1::text IS NULL OR $1 = '' OR actor_id = $1)
  AND ($2::text IS NULL OR $2 = '' OR target_type = $2)
  AND ($3::text IS NULL OR $3 = '' OR target_id = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)
ORDER BY created_at DESC
LIMIT $6
`

type ListAuditEventsParams struct {
	Column1 string             `json:"column_1"`
	Column2 string             `json:"column_2"`
	Column3 string             `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
	Column5 pgtype.Timestamptz `json:"column_5"`
	Limit   int32              `json:"limit"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByService = `-- name: ListDeploymentsByService :many
SELECT id, service_id, commit_sha, status, logs_ref, created_at FROM deployments
WHERE service_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByService(ctx context.Context, serviceID pgtype.UUID) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.CommitSha,
			&i.Status,
			&i.LogsRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueScheduledTasks = `-- name: ListDueScheduledTasks :many
SELECT id, service_id, owner_id, name, cron_expr, action, status, last_run_at, next_run_at, last_result, created_at, updated_at FROM scheduled_tasks
WHERE status = 'active'
  AND next_run_at IS NOT NULL
  AND next_run_at <= $1
ORDER BY next_run_at ASC
LIMIT 50
`

func (q *Queries) ListDueScheduledTasks(ctx context.Context, nextRunAt pgtype.Timestamptz) ([]ScheduledTask, error) {
	rows, err := q.db.Query(ctx, listDueScheduledTasks, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledTask
	for rows.Next() {
		var i ScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.OwnerID,
			&i.Name,
			&i.CronExpr,
			&i.Action,
			&i.Status,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.LastResult,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, region, agent_token_hash, status, capacity, created_at, updated_at FROM nodes
ORDER BY created_at DESC
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Region,
			&i.AgentTokenHash,
			&i.Status,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledTasksByService = `-- name: ListScheduledTasksByService :many
SELECT id, service_id, owner_id, name, cron_expr, action, status, last_run_at, next_run_at, last_result, created_at, updated_at FROM scheduled_tasks
WHERE service_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListScheduledTasksByService(ctx context.Context, serviceID pgtype.UUID) ([]ScheduledTask, error) {
	rows, err := q.db.Query(ctx, listScheduledTasksByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledTask
	for rows.Next() {
		var i ScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.OwnerID,
			&i.Name,
			&i.CronExpr,
			&i.Action,
			&i.Status,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.LastResult,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByNode = `-- name: ListServicesByNode :many
SELECT id, owner_id, team_id, name, type, status, node_id, resource_limits, config, tags, created_at, updated_at FROM services
WHERE node_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListServicesByNode(ctx context.Context, nodeID pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.TeamID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.NodeID,
			&i.ResourceLimits,
			&i.Config,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserServices = `-- name: ListUserServices :many
SELECT id, owner_id, team_id, name, type, status, node_id, resource_limits, config, tags, created_at, updated_at FROM services
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserServices(ctx context.Context, ownerID string) ([]Service, error) {
	rows, err := q.db.Query(ctx, listUserServices, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.TeamID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.NodeID,
			&i.ResourceLimits,
			&i.Config,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeServiceLoads = `-- name: NodeServiceLoads :many
SELECT
  node_id,
  COUNT(*)::bigint AS service_count,
  COALESCE(SUM((resource_limits->>'memory_mb')::bigint), 0)::bigint AS total_memory_mb
FROM services
WHERE node_id IS NOT NULL
  AND status NOT IN ('STOPPED', 'CRASHED')
GROUP BY node_id
`

type NodeServiceLoadsRow struct {
	NodeID        pgtype.UUID `json:"node_id"`
	ServiceCount  int64       `json:"service_count"`
	TotalMemoryMb int64       `json:"total_memory_mb"`
}

func (q *Queries) NodeServiceLoads(ctx context.Context) ([]NodeServiceLoadsRow, error) {
	rows, err := q.db.Query(ctx, nodeServiceLoads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeServiceLoadsRow
	for rows.Next() {
		var i NodeServiceLoadsRow
		if err := rows.Scan(&i.NodeID, &i.ServiceCount, &i.TotalMemoryMb); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchApiKey = `-- name: TouchApiKey :exec
UPDATE api_keys
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchApiKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchApiKey, id)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments
SET status = $2,
    logs_ref = $3
WHERE id = $1
RETURNING id, service_id, commit_sha, status, logs_ref, created_at
`

type UpdateDeploymentStatusParams struct {
	ID      pgtype.UUID  `json:"id"`
	Status  DeployStatus `json:"status"`
	LogsRef *string      `json:"logs_ref"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeploymentStatus, arg.ID, arg.Status, arg.LogsRef)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.CommitSha,
		&i.Status,
		&i.LogsRef,
		&i.CreatedAt,
	)
	return i, err
}

const updateNodeCapacity = `-- name: UpdateNodeCapacity :one
UPDATE nodes
SET capacity = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, region, agent_token_hash, status, capacity, created_at, updated_at
`

type UpdateNodeCapacityParams struct {
	ID       pgtype.UUID         `json:"id"`
	Capacity domain.NodeCapacity `json:"capacity"`
}

func (q *Queries) UpdateNodeCapacity(ctx context.Context, arg UpdateNodeCapacityParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeCapacity, arg.ID, arg.Capacity)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.AgentTokenHash,
		&i.Status,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNodeStatus = `-- name: UpdateNodeStatus :one
UPDATE nodes
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, region, agent_token_hash, status, capacity, created_at, updated_at
`

type UpdateNodeStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeStatus, arg.ID, arg.Status)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.AgentTokenHash,
		&i.Status,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNodeTokenHash = `-- name: UpdateNodeTokenHash :one
UPDATE nodes
SET agent_token_hash = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, region, agent_token_hash, status, capacity, created_at, updated_at
`

type UpdateNodeTokenHashParams struct {
	ID             pgtype.UUID `json:"id"`
	AgentTokenHash string      `json:"agent_token_hash"`
}

func (q *Queries) UpdateNodeTokenHash(ctx context.Context, arg UpdateNodeTokenHashParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeTokenHash, arg.ID, arg.AgentTokenHash)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.AgentTokenHash,
		&i.Status,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScheduledTaskDone = `-- name: UpdateScheduledTaskDone :one
UPDATE scheduled_tasks
SET status = 'active',
    last_result = $2,
    next_run_at = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, service_id, owner_id, name, cron_expr, action, status, last_run_at, next_run_at, last_result, created_at, updated_at
`

type UpdateScheduledTaskDoneParams struct {
	ID         pgtype.UUID        `json:"id"`
	LastResult *string            `json:"last_result"`
	NextRunAt  pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateScheduledTaskDone(ctx context.Context, arg UpdateScheduledTaskDoneParams) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, updateScheduledTaskDone, arg.ID, arg.LastResult, arg.NextRunAt)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.OwnerID,
		&i.Name,
		&i.CronExpr,
		&i.Action,
		&i.Status,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.LastResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScheduledTaskRunning = `-- name: UpdateScheduledTaskRunning :one
UPDATE scheduled_tasks
SET status = 'running',
    last_run_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, service_id, owner_id, name, cron_expr, action, status, last_run_at, next_run_at, last_result, created_at, updated_at
`

func (q *Queries) UpdateScheduledTaskRunning(ctx context.Context, id pgtype.UUID) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, updateScheduledTaskRunning, id)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.OwnerID,
		&i.Name,
		&i.CronExpr,
		&i.Action,
		&i.Status,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.LastResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceConfig = `-- name: UpdateServiceConfig :one
UPDATE services
SET resource_limits = $2,
    config = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, owner_id, team_id, name, type, status, node_id, resource_limits, config, tags, created_at, updated_at
`

type UpdateServiceConfigParams struct {
	ID             pgtype.UUID           `json:"id"`
	ResourceLimits domain.ResourceLimits `json:"resource_limits"`
	Config         domain.ServiceConfig  `json:"config"`
}

func (q *Queries) UpdateServiceConfig(ctx context.Context, arg UpdateServiceConfigParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateServiceConfig, arg.ID, arg.ResourceLimits, arg.Config)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TeamID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.NodeID,
		&i.ResourceLimits,
		&i.Config,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceStatus = `-- name: UpdateServiceStatus :one
UPDATE services
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, owner_id, team_id, name, type, status, node_id, resource_limits, config, tags, created_at, updated_at
`

type UpdateServiceStatusParams struct {
	ID     pgtype.UUID   `json:"id"`
	Status ServiceStatus `json:"status"`
}

func (q *Queries) UpdateServiceStatus(ctx context.Context, arg UpdateServiceStatusParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateServiceStatus, arg.ID, arg.Status)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TeamID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.NodeID,
		&i.ResourceLimits,
		&i.Config,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
