import type { DeployTemplate } from "./types";

/** Phase 1 starter templates (plan section 9) — all Docker-backed. */
export const DEPLOY_TEMPLATES: DeployTemplate[] = [
  {
    id: "minecraft",
    name: "Minecraft Server",
    type: "game",
    description: "Java Edition Minecraft server. Bukkit-based (Purpur/Spigot) support plugins. Mod loaders (Fabric/Forge/NeoForge/Quilt) support mods.",
    defaultImage: "eclipse-temurin:21-jre-alpine",
    defaultPorts: ["0.0.0.0:25565:25565/tcp"],
    defaultMemoryMb: 4096,
    defaultCpuThreads: 2,
    defaultDiskGb: 30,
    defaultStartupCmd: 'cd /mnt/server\nif ls forge-*-shim.jar 2>/dev/null | head -1 | grep -q .; then\n  exec java -Xmx${MEMORY}M -Xms${MEMORY}M ${JVM_FLAGS} @user_jvm_args.txt @libraries/net/minecraftforge/forge/*/unix_args.txt nogui\nelif ls neoforge-*-shim.jar 2>/dev/null | head -1 | grep -q .; then\n  exec java -Xmx${MEMORY}M -Xms${MEMORY}M ${JVM_FLAGS} @user_jvm_args.txt @libraries/net/neoforged/neoforge/*/unix_args.txt nogui\nelif [ -f server.jar ]; then\n  exec java -Xmx${MEMORY}M -Xms${MEMORY}M ${JVM_FLAGS} -jar server.jar nogui\nelse\n  echo "[Vivox] ERROR: No server JAR found. Trigger a reinstall from the panel." >&2\n  sleep 60\nfi',
    env: [
      {
        key: "FRAMEWORK",
        label: "Server Framework",
        value: "Vanilla",
        fieldType: "select",
        options: "Vanilla, Purpur, Fabric, Forge, NeoForge, Quilt, Spigot",
        description: "Bukkit-based (Purpur/Spigot) support plugins. Mod loaders (Fabric/Forge/NeoForge/Quilt) support mods.",
        required: true,
      },
      {
        key: "MC_VERSION",
        label: "Minecraft Version",
        value: "1.21.4",
        fieldType: "text",
        description: "Minecraft version string, e.g. 1.21.4.",
        required: true,
      },
      {
        key: "MEMORY",
        label: "Java Heap (MB)",
        value: "3072",
        fieldType: "number",
        description: "JVM -Xmx/-Xms in megabytes. Min 1024. Use 4096+ for modpacks.",
        required: true,
      },
      {
        key: "FABRIC_LOADER_VERSION",
        label: "Fabric Loader Version",
        value: "latest",
        fieldType: "text",
        description: "Fabric loader version. 'latest' auto-selects the newest stable.",
      },
      {
        key: "FORGE_VERSION",
        label: "Forge Version",
        value: "",
        fieldType: "text",
        description: "Forge version (leave blank for latest recommended). e.g. 47.3.12",
      },
      {
        key: "NEOFORGE_VERSION",
        label: "NeoForge Version",
        value: "",
        fieldType: "text",
        description: "NeoForge version (leave blank for latest). e.g. 21.4.75",
      },
      {
        key: "QUILT_LOADER_VERSION",
        label: "Quilt Loader Version",
        value: "latest",
        fieldType: "text",
        description: "Quilt loader version. 'latest' auto-selects the newest stable.",
      },
      {
        key: "BUILD_NUMBER",
        label: "Purpur Build Number",
        value: "latest",
        fieldType: "text",
        description: "Purpur build number. 'latest' always fetches the newest build.",
      },
      {
        key: "MOTD",
        label: "Server MOTD",
        value: "A Vivox Minecraft Server",
        fieldType: "text",
        description: "Message shown in the Minecraft server browser.",
      },
      {
        key: "MAX_PLAYERS",
        label: "Max Players",
        value: "20",
        fieldType: "number",
      },
      {
        key: "DIFFICULTY",
        label: "Difficulty",
        value: "normal",
        fieldType: "select",
        options: "peaceful, easy, normal, hard",
      },
      {
        key: "GAMEMODE",
        label: "Default Gamemode",
        value: "survival",
        fieldType: "select",
        options: "survival, creative, adventure, spectator",
      },
      {
        key: "ONLINE_MODE",
        label: "Online Mode",
        value: "true",
        fieldType: "select",
        options: "true, false",
        description: "Set false for offline/cracked servers.",
      },
      {
        key: "LEVEL_SEED",
        label: "World Seed",
        value: "",
        fieldType: "text",
        description: "Optional world generation seed. Leave blank for random.",
      },
    ],
  },
  {
    id: "rust",
    name: "Rust Server",
    type: "game",
    description: "Rust dedicated server (SturdyStubs AIO egg) with Carbon/Oxide/Vanilla support.",
    defaultImage: "ghcr.io/sturdystubs/aioegg:production",
    defaultPorts: [
      "0.0.0.0:28015:28015/udp",
      "0.0.0.0:28016:28016/tcp",
      "0.0.0.0:28017:28017/udp",
    ],
    defaultMemoryMb: 8192,
    defaultCpuThreads: 2,
    defaultDiskGb: 50,
    defaultStartupCmd:
      './RustDedicated -batchmode -nographics $( FW="$(echo "${FRAMEWORK}" | tr \'[:upper:]\' \'[:lower:]\')"; [ "$FW" = "oxide" ] && printf %s "+oxide.directory \\"${MODDING_ROOT}\\"" || { [ "$FW" = "vanilla" ] && printf %s "" || printf %s "-carbon.rootdir \\"${MODDING_ROOT}\\""; } ) +server.port ${SERVER_PORT} +server.queryport ${QUERY_PORT} +server.identity "${SERVER_IDENTITY}" +server.gamemode "${GAMEMODE}" +server.level "${LEVEL}" +rcon.port ${RCON_PORT} +rcon.ip 0.0.0.0 +rcon.web true +server.hostname "${HOSTNAME}" +server.description "${DESCRIPTION}" +server.url "${SERVER_URL}" +server.headerimage "${SERVER_IMG}" +server.logoimage "${SERVER_LOGO}" +server.maxplayers ${MAX_PLAYERS} +rcon.password "${RCON_PASS}" +server.saveinterval ${SAVEINTERVAL} +app.port ${APP_PORT} $( [ -z "${MAP_URL}" ] && printf %s "+server.worldsize \\"${WORLD_SIZE}\\" +server.seed \\"${WORLD_SEED}\\"" || printf %s "+server.levelurl \\"${MAP_URL}\\"" ) $( [ -n "${APP_PUBLIC_IP}" ] && printf %s "+app.publicip \\"${APP_PUBLIC_IP}\\"" ) $( [ -n "${SERVER_TAGS}" ] && printf %s "+server.tags \\"${SERVER_TAGS}\\"" ) $( d="logs/console.log"; mkdir -p "$(dirname "$d")" ) -logfile "logs/console.log" ${ADDITIONAL_ARGS}',
    env: [
      // ── Required / user-configurable ─────────────────────────────────────
      {
        key: "HOSTNAME",
        label: "Server name",
        value: "A Vivox Rust Server",
        required: true,
        fieldType: "text",
        description: "Public server list title (max 60 chars).",
      },
      {
        key: "MAX_PLAYERS",
        label: "Max players",
        value: "100",
        fieldType: "number",
        required: true,
        description: "Maximum concurrent players.",
      },
      {
        key: "RCON_PASS",
        label: "RCON password",
        value: "CHANGEME",
        fieldType: "password",
        required: true,
        description: "Strong password required for RCON and server startup.",
      },
      {
        key: "FRAMEWORK",
        label: "Modding framework",
        value: "Carbon",
        options: "Vanilla, Oxide, Carbon, Carbon-Minimal",
        fieldType: "select",
        required: true,
        description: "Vanilla, Oxide, or Carbon.",
      },
      // ── Optional configurable ─────────────────────────────────────────────
      {
        key: "DESCRIPTION",
        label: "Description",
        value: "Powered by Vivox",
        fieldType: "text",
        description: "Server description shown in browser.",
      },
      {
        key: "GAMEMODE",
        label: "Gamemode",
        value: "vanilla",
        options: "vanilla, survival, softcore, hardcore",
        fieldType: "select",
      },
      {
        key: "WORLD_SIZE",
        label: "World size",
        value: "3000",
        fieldType: "number",
        description: "Procedural map size (ignored when a custom map URL is set).",
      },
      {
        key: "WORLD_SEED",
        label: "World seed",
        value: "1234",
        fieldType: "text",
        description: "Procedural map seed.",
      },
      {
        key: "MAP_URL",
        label: "Custom map URL",
        value: "",
        fieldType: "text",
        description: "Optional direct download URL for a custom map. Overrides world size/seed.",
      },
      {
        key: "MODDING_ROOT",
        label: "Modding root directory",
        value: "carbon",
        fieldType: "text",
        description: "Framework data directory (carbon or oxide).",
      },
      // ── Network / ports ───────────────────────────────────────────────────
      { key: "SERVER_PORT", label: "Game port", value: "28015", fieldType: "number" },
      { key: "QUERY_PORT", label: "Query port", value: "28017", fieldType: "number" },
      { key: "RCON_PORT", label: "RCON port", value: "28016", fieldType: "number" },
      { key: "APP_PORT", label: "Companion app port (-1 = disabled)", value: "-1", fieldType: "number" },
      { key: "APP_PUBLIC_IP", label: "App public IP", value: "", fieldType: "text" },
      // ── Server identity / metadata ────────────────────────────────────────
      { key: "SERVER_IDENTITY", label: "Server identity folder", value: "rust", fieldType: "text" },
      { key: "LEVEL", label: "Map level", value: "Procedural Map", fieldType: "text" },
      { key: "SERVER_TAGS", label: "Server tags", value: "vanilla", fieldType: "text" },
      { key: "SERVER_URL", label: "Server URL", value: "", fieldType: "text" },
      { key: "SERVER_IMG", label: "Header image URL", value: "", fieldType: "text" },
      { key: "SERVER_LOGO", label: "Logo image URL", value: "", fieldType: "text" },
      { key: "SAVEINTERVAL", label: "Save interval (seconds)", value: "600", fieldType: "number" },
      { key: "ADDITIONAL_ARGS", label: "Additional launch args", value: "", fieldType: "text" },
      // ── Installation ──────────────────────────────────────────────────────
      {
        key: "DOWNLOAD_METHOD",
        label: "Download method",
        value: "SteamCMD",
        options: "SteamCMD, DepotDownloader",
        fieldType: "select",
      },
      {
        key: "VERSION",
        label: "Branch / Version",
        value: "public",
        fieldType: "select",
        options: "public, release, staging, aux01, aux02",
        description: "Steam branch. Use 'public' for live servers.",
      },
      { key: "AUTO_UPDATE", label: "Auto-update on start", value: "1", fieldType: "select", options: "1, 0" },
      { key: "VALIDATE", label: "Validate files on update", value: "1", fieldType: "select", options: "1, 0" },
      { key: "FRAMEWORK_UPDATE", label: "Update framework on start", value: "1", fieldType: "select", options: "1, 0", description: "Enable/disable Carbon or Oxide framework update on each startup." },
      { key: "CHAOS_EXT", label: "ChaosCode extension", value: "0", fieldType: "select", options: "0, 1", description: "Install the ChaosCode extension (Carbon only)." },
      { key: "DISCORD_EXT", label: "Discord extension", value: "0", fieldType: "select", options: "0, 1", description: "Install the Discord Extension." },
      { key: "RUSTEDIT_EXT", label: "RustEdit extension", value: "0", fieldType: "select", options: "0, 1", description: "Install the RustEdit Extension for custom map support." },
      { key: "LOG_FILE", label: "Log file path", value: "", fieldType: "text", description: "Override log file location. Leave blank for default (logs/console.log)." },
    ],
  },
  {
    id: "docker",
    name: "Generic Docker App",
    type: "docker",
    description: "Run any public image with custom ports and environment.",
    defaultImage: "",
    defaultPorts: [],
    defaultMemoryMb: 512,
    defaultCpuThreads: 1,
    defaultDiskGb: 5,
    env: [],
  },
  {
    id: "static",
    name: "Static Site",
    type: "static",
    description: "nginx serving uploaded static files.",
    defaultImage: "nginx:alpine",
    defaultPorts: ["8080:80/tcp"],
    defaultMemoryMb: 256,
    defaultCpuThreads: 1,
    defaultDiskGb: 2,
    env: [],
  },
];

export function getTemplate(id: string): DeployTemplate | undefined {
  return DEPLOY_TEMPLATES.find((t) => t.id === id);
}
